#!/bin/sh
service ssh restart               # because the process stops after starting at
                                  #   boot
cd /opt/TitanVision/
python hsl_auto.py --debug-level -1 --discard 20 --nofile
python main.py &
exit 0

# vim:ts=2:sw=2:nospell
