#!/bin/sh
service ssh restart       # because the service stops after starting at
                          #   boot for some unknown reason
cd /opt/TitanVision/
python hsl_auto.py --debug-level -1 --discard 20 --nofile # snaps a pic at
                                                          # boot time and
                                                          # saves it
python main.py &          # runs the vision processing and outputs values
                          #   to networktables in the background
exit 0

# vim:ts=2:sw=2:nospell
